### ISSUE TITLE
not_implemented is undefined

### ISSUE THREAD

**Issue by esparkman** [paweljw/bookstore-backend#4]
Loving the Article Series. But I'm seeing an issue where not_implemented is undefined. Not sure what I'm missing.

**Comment by paweljw** [comment]
Thanks!

It seems that I've made a mistake of following what I know blindly. In a "regular" Rails application, `not_implemented` will be present:

```
5.0.2 @ 2.4.0 (main)>not_implemented
NotImplementedError: class Object must implement abstract method '()'.
```

If we dig for the source, we'll see this:

```
5.0.2 @ 2.4.0 (main)>show-source not_implemented

From: /Users/pjw/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/erubis-2.7.0/lib/erubis/util.rb @ line 11:
Owner: Kernel
Visibility: private
Number of lines: 9

def not_implemented     #:doc:
  backtrace = caller()
  method_name = (backtrace.shift =~ /`(\w+)'$/) && $1
  mesg = "class #{self.class.name} must implement abstract method '#{method_name}()'."
  #mesg = "#{self.class.name}##{method_name}() is not implemented."
  err = NotImplementedError.new mesg
  err.set_backtrace backtrace
  raise err
end
```

So this is defined in erubis, which is pulled in by actionview. In an API app erubis is not pulled in, so `not_implemented` is missing.

I always assumed that this method is defined by ActiveSupport :) Thanks for pointing this out, I hope we've both learned something today - I certainly did! I'll fix the code (whenever I get the time to do that) to just `throw NotImplementedError` instead.

**Comment by esparkman** [comment]
I definitely learned something new from it. Maybe I'll attempt a PR for you or something. Looking forward to the Vue portion as well.

I have a Rails API + Vue app going using Knock at the moment. I'm always down to figure out how to take some of the magic out of it though.

Thanks for quick and informative response.
